version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgress-demo-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/

volumes:
  pgdata:
    driver: local