name: Build and deploy API Docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate docs html using Redoc
        run: |
          npm install -g redoc-cli
          redoc-cli bundle docs/openapi.json --output generated/index.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: generated
          token: ${{ secrets.GITHUB_TOKEN }}
      
